[package]
name = "hyperpuzzle-notation"
authors = ["Andrew Farkas"]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Hypercubers/hyperpuzzle-notation/"

[dependencies]
